services:
  - type: web
    name: latency-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy && npm run db:seed
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: 3333
      - key: JUDGE0_URL
        value: https://ce.judge0.com
      - key: ANTHROPIC_API_KEY
        sync: false
