import { Language } from '@prisma/client';

/**
 * `helpSignature` por linguagem, na mesma ordem de `PROBLEMS` (ver
 * problems.ts) — índice 0..24 = fácil, 25..34 = médio, 35..39 = difícil.
 * É só o hint mostrado no "modo ajuda" (renderizado em canvas, não copiável);
 * o jogador escreve a solução completa (leitura de stdin + print) do zero.
 */
export const SIGNATURES: Record<Language, string[]> = {
  JAVASCRIPT: [
    'function somar(a, b) { /* ... */ }',
    'function subtrair(a, b) { /* ... */ }',
    'function multiplicar(a, b) { /* ... */ }',
    'function divisaoInteira(a, b) { /* retorna [quociente, resto] */ }',
    'function maior(a, b) { /* ... */ }',
    'function maiorDeTres(a, b, c) { /* ... */ }',
    'function parOuImpar(n) { /* retorna "par" ou "impar" */ }',
    'function sinal(n) { /* retorna "positivo", "negativo" ou "zero" */ }',
    'function tabuada(n) { /* imprime de 1 a 10 */ }',
    'function contagemRegressiva(n) { /* imprime de n até 1 */ }',
    'function somaAte(n) { /* soma de 1 até n */ }',
    'function fatorial(n) { /* iterativo */ }',
    'function inverterString(s) { /* ... */ }',
    'function contarVogais(s) { /* ... */ }',
    'function ehPrimo(n) { /* ... */ }',
    'function maiorDoArray(arr) { /* ... */ }',
    'function somarArray(arr) { /* ... */ }',
    'function media(arr) { /* usar toFixed(2) */ }',
    'function contarPares(arr) { /* ... */ }',
    'function inverterArray(arr) { /* ... */ }',
    'function buscaLinear(arr, alvo) { /* ... */ }',
    'function concatenar(a, b) { /* ... */ }',
    'function comprimento(s) { /* ... */ }',
    'function celsiusParaFahrenheit(c) { /* ... */ }',
    'function trocar(a, b) { /* retorna [b, a] */ }',
    'function ehPalindromo(s) { /* ... */ }',
    'function bubbleSort(arr) { /* ... */ }',
    'function buscaBinaria(arr, alvo) { /* array já ordenado */ }',
    'function mdc(a, b) { /* ... */ }',
    'function mmc(a, b) { /* ... */ }',
    'function contarDigitos(n) { /* ... */ }',
    'function somaDigitos(n) { /* ... */ }',
    'function reverterNumero(n) { /* ... */ }',
    'function fibonacci(n) { /* retorna array com n termos */ }',
    'function ehAnagrama(a, b) { /* ... */ }',
    'function fibonacciRecursivo(n) { /* recursão */ }',
    'function hanoi(n, origem, destino, auxiliar) { /* recursão, imprime movimentos */ }',
    'function quicksort(arr) { /* recursão + particionamento */ }',
    'function crivoDeEratostenes(n) { /* retorna array de primos até n */ }',
    'function frequenciaCaracteres(s) { /* mapa ordenado pela 1ª ocorrência */ }',
  ],
  TYPESCRIPT: [
    'function somar(a: number, b: number): number { /* ... */ }',
    'function subtrair(a: number, b: number): number { /* ... */ }',
    'function multiplicar(a: number, b: number): number { /* ... */ }',
    'function divisaoInteira(a: number, b: number): [number, number] { /* [quociente, resto] */ }',
    'function maior(a: number, b: number): number { /* ... */ }',
    'function maiorDeTres(a: number, b: number, c: number): number { /* ... */ }',
    'function parOuImpar(n: number): string { /* "par" ou "impar" */ }',
    'function sinal(n: number): string { /* "positivo" | "negativo" | "zero" */ }',
    'function tabuada(n: number): void { /* imprime de 1 a 10 */ }',
    'function contagemRegressiva(n: number): void { /* imprime de n até 1 */ }',
    'function somaAte(n: number): number { /* ... */ }',
    'function fatorial(n: number): number { /* iterativo */ }',
    'function inverterString(s: string): string { /* ... */ }',
    'function contarVogais(s: string): number { /* ... */ }',
    'function ehPrimo(n: number): boolean { /* ... */ }',
    'function maiorDoArray(arr: number[]): number { /* ... */ }',
    'function somarArray(arr: number[]): number { /* ... */ }',
    'function media(arr: number[]): string { /* usar toFixed(2) */ }',
    'function contarPares(arr: number[]): number { /* ... */ }',
    'function inverterArray(arr: number[]): number[] { /* ... */ }',
    'function buscaLinear(arr: number[], alvo: number): boolean { /* ... */ }',
    'function concatenar(a: string, b: string): string { /* ... */ }',
    'function comprimento(s: string): number { /* ... */ }',
    'function celsiusParaFahrenheit(c: number): number { /* ... */ }',
    'function trocar(a: number, b: number): [number, number] { /* [b, a] */ }',
    'function ehPalindromo(s: string): boolean { /* ... */ }',
    'function bubbleSort(arr: number[]): number[] { /* ... */ }',
    'function buscaBinaria(arr: number[], alvo: number): number { /* array já ordenado */ }',
    'function mdc(a: number, b: number): number { /* ... */ }',
    'function mmc(a: number, b: number): number { /* ... */ }',
    'function contarDigitos(n: number): number { /* ... */ }',
    'function somaDigitos(n: number): number { /* ... */ }',
    'function reverterNumero(n: number): number { /* ... */ }',
    'function fibonacci(n: number): number[] { /* n termos */ }',
    'function ehAnagrama(a: string, b: string): boolean { /* ... */ }',
    'function fibonacciRecursivo(n: number): number { /* recursão */ }',
    'function hanoi(n: number, origem: string, destino: string, auxiliar: string): void { /* recursão, imprime movimentos */ }',
    'function quicksort(arr: number[]): number[] { /* recursão + particionamento */ }',
    'function crivoDeEratostenes(n: number): number[] { /* primos até n */ }',
    'function frequenciaCaracteres(s: string): Map<string, number> { /* ordenado pela 1ª ocorrência */ }',
  ],
  CSHARP: [
    'static int Somar(int a, int b) { /* ... */ }',
    'static int Subtrair(int a, int b) { /* ... */ }',
    'static int Multiplicar(int a, int b) { /* ... */ }',
    'static (int quociente, int resto) DivisaoInteira(int a, int b) { /* ... */ }',
    'static int Maior(int a, int b) { /* ... */ }',
    'static int MaiorDeTres(int a, int b, int c) { /* ... */ }',
    'static string ParOuImpar(int n) { /* "par" ou "impar" */ }',
    'static string Sinal(int n) { /* "positivo", "negativo" ou "zero" */ }',
    'static void Tabuada(int n) { /* imprime de 1 a 10 */ }',
    'static void ContagemRegressiva(int n) { /* imprime de n até 1 */ }',
    'static int SomaAte(int n) { /* ... */ }',
    'static long Fatorial(int n) { /* iterativo */ }',
    'static string InverterString(string s) { /* ... */ }',
    'static int ContarVogais(string s) { /* ... */ }',
    'static bool EhPrimo(int n) { /* ... */ }',
    'static int MaiorDoArray(int[] arr) { /* ... */ }',
    'static int SomarArray(int[] arr) { /* ... */ }',
    'static string Media(int[] arr) { /* usar .ToString("F2") */ }',
    'static int ContarPares(int[] arr) { /* ... */ }',
    'static int[] InverterArray(int[] arr) { /* ... */ }',
    'static bool BuscaLinear(int[] arr, int alvo) { /* ... */ }',
    'static string Concatenar(string a, string b) { /* ... */ }',
    'static int Comprimento(string s) { /* ... */ }',
    'static int CelsiusParaFahrenheit(int c) { /* ... */ }',
    'static (int, int) Trocar(int a, int b) { /* (b, a) */ }',
    'static bool EhPalindromo(string s) { /* ... */ }',
    'static int[] BubbleSort(int[] arr) { /* ... */ }',
    'static int BuscaBinaria(int[] arr, int alvo) { /* array já ordenado */ }',
    'static int Mdc(int a, int b) { /* ... */ }',
    'static int Mmc(int a, int b) { /* ... */ }',
    'static int ContarDigitos(int n) { /* ... */ }',
    'static int SomaDigitos(int n) { /* ... */ }',
    'static int ReverterNumero(int n) { /* ... */ }',
    'static int[] Fibonacci(int n) { /* n termos */ }',
    'static bool EhAnagrama(string a, string b) { /* ... */ }',
    'static long FibonacciRecursivo(int n) { /* recursão */ }',
    'static void Hanoi(int n, string origem, string destino, string auxiliar) { /* recursão, imprime movimentos */ }',
    'static int[] Quicksort(int[] arr) { /* recursão + particionamento */ }',
    'static List<int> CrivoDeEratostenes(int n) { /* primos até n */ }',
    'static Dictionary<char, int> FrequenciaCaracteres(string s) { /* ordenado pela 1ª ocorrência */ }',
  ],
  C: [
    'int somar(int a, int b) { /* ... */ }',
    'int subtrair(int a, int b) { /* ... */ }',
    'int multiplicar(int a, int b) { /* ... */ }',
    'void divisaoInteira(int a, int b, int *quociente, int *resto) { /* ... */ }',
    'int maior(int a, int b) { /* ... */ }',
    'int maiorDeTres(int a, int b, int c) { /* ... */ }',
    'const char *parOuImpar(int n) { /* "par" ou "impar" */ }',
    'const char *sinal(int n) { /* "positivo", "negativo" ou "zero" */ }',
    'void tabuada(int n) { /* imprime de 1 a 10 */ }',
    'void contagemRegressiva(int n) { /* imprime de n até 1 */ }',
    'int somaAte(int n) { /* ... */ }',
    'long fatorial(int n) { /* iterativo */ }',
    'void inverterString(char *s) { /* in-place */ }',
    'int contarVogais(const char *s) { /* ... */ }',
    'int ehPrimo(int n) { /* retorna 1 ou 0 */ }',
    'int maiorDoArray(int *arr, int n) { /* ... */ }',
    'int somarArray(int *arr, int n) { /* ... */ }',
    'double media(int *arr, int n) { /* ... */ }',
    'int contarPares(int *arr, int n) { /* ... */ }',
    'void inverterArray(int *arr, int n) { /* in-place */ }',
    'int buscaLinear(int *arr, int n, int alvo) { /* retorna 1 ou 0 */ }',
    'void concatenar(char *destino, const char *a, const char *b) { /* ... */ }',
    'int comprimento(const char *s) { /* ... */ }',
    'int celsiusParaFahrenheit(int c) { /* ... */ }',
    'void trocar(int *a, int *b) { /* ponteiros */ }',
    'int ehPalindromo(const char *s) { /* retorna 1 ou 0 */ }',
    'void bubbleSort(int *arr, int n) { /* in-place */ }',
    'int buscaBinaria(int *arr, int n, int alvo) { /* array já ordenado */ }',
    'int mdc(int a, int b) { /* ... */ }',
    'int mmc(int a, int b) { /* ... */ }',
    'int contarDigitos(int n) { /* ... */ }',
    'int somaDigitos(int n) { /* ... */ }',
    'int reverterNumero(int n) { /* ... */ }',
    'void fibonacci(int n, int *resultado) { /* preenche array com n termos */ }',
    'int ehAnagrama(const char *a, const char *b) { /* retorna 1 ou 0 */ }',
    'long fibonacciRecursivo(int n) { /* recursão */ }',
    'void hanoi(int n, char origem, char destino, char auxiliar) { /* recursão, imprime movimentos */ }',
    'void quicksort(int *arr, int inicio, int fim) { /* recursão + particionamento */ }',
    'int crivoDeEratostenes(int n, int *primos) { /* preenche array de primos, retorna quantidade */ }',
    'void frequenciaCaracteres(const char *s) { /* imprime "char:qtd" na ordem de 1ª ocorrência */ }',
  ],
};
